### ISSUE TITLE
Templates Example?

### ISSUE THREAD

**Issue by jcrawford** [yanneves/metalsmith-collections-archive#1]
Could you show an example of how to structure the template for this?  I have a template file being used but I am not sure how to access the year / month / day in the template so that it will be generated properly in the html document.

**Comment by yanneves** [comment]
Glad you pointed this out! I think this was missing from the documentation.

Added an example in the `README.md` https://github.com/yanneves/metalsmith-collections-archive#example-layout

Let me know if you have any further questions.
